insert into JEUX_THEMES values ( 'Gloomhaven', 'Antiquité ') ;
insert into JEUX_THEMES values ( 'Pandemic Legacy: Season 1', 'Espace') ;
insert into JEUX_THEMES values ( 'Brass: Birmingham', 'Enquete') ;
insert into JEUX_THEMES values ( 'Terraforming Mars', 'Connaissances') ;
insert into JEUX_THEMES values ( 'Twilight Imperium: Fourth Edition', 'Histoire') ;
insert into JEUX_THEMES values ( 'Gloomhaven: Jaws of the Lion', 'Histoire') ;
insert into JEUX_THEMES values ( 'Through the Ages: A New Story of Civilization', 'Aventure') ;
insert into JEUX_THEMES values ( 'Gaia Project', 'Abstrait') ;
insert into JEUX_THEMES values ( 'Star Wars: Rebellion', 'Construction') ;
insert into JEUX_THEMES values ( 'Twilight Struggle', 'Antiquité ') ;
insert into JEUX_THEMES values ( 'Great Western Trail', 'Espace') ;
insert into JEUX_THEMES values ( 'War of the Ring: Second Edition', 'Construction') ;
insert into JEUX_THEMES values ( 'Spirit Island', 'Enfant') ;
insert into JEUX_THEMES values ( 'Scythe', 'Aventure') ;
insert into JEUX_THEMES values ( 'The Castles of Burgundy', 'Survie') ;
insert into JEUX_THEMES values ( 'Terra Mystica', 'Connaissances') ;
insert into JEUX_THEMES values ( '7 Wonders Duel', 'Fanstastique ') ;
insert into JEUX_THEMES values ( 'Concordia', 'Merveilleux') ;
insert into JEUX_THEMES values ( 'Brass: Lancashire', 'Survie') ;
insert into JEUX_THEMES values ( 'Wingspan', 'Mytholoie') ;
insert into JEUX_THEMES values ( 'A Feast for Odin', 'Enquete') ;
insert into JEUX_THEMES values ( 'Arkham Horror: The Card Game', 'Fanstastique ') ;
insert into JEUX_THEMES values ( 'Viticulture Essential Edition', 'Antiquité ') ;
insert into JEUX_THEMES values ( 'Nemesis', 'Espace') ;
insert into JEUX_THEMES values ( 'Orléans', 'Survie') ;
insert into JEUX_THEMES values ( 'Mage Knight Board Game', 'Enquete') ;
insert into JEUX_THEMES values ( 'Root', 'Merveilleux') ;
insert into JEUX_THEMES values ( 'Puerto Rico', 'Connaissances') ;
insert into JEUX_THEMES values ( 'Food Chain Magnate', 'Enfant') ;
insert into JEUX_THEMES values ( 'Caverna: The Cave Farmers', 'Mathematiques') ;
insert into JEUX_THEMES values ( 'Agricola', 'Enfant') ;
insert into JEUX_THEMES values ( 'Blood Rage', 'Connaissances') ;
insert into JEUX_THEMES values ( 'Mansions of Madness: Second Edition', 'Mathematiques') ;
insert into JEUX_THEMES values ( 'The 7th Continent', 'Mytholoie') ;
insert into JEUX_THEMES values ( 'Pandemic Legacy: Season 2', 'Abstrait') ;
insert into JEUX_THEMES values ( 'Everdell', 'Aventure') ;
insert into JEUX_THEMES values ( 'Maracaibo', 'Fantastique') ;
insert into JEUX_THEMES values ( 'Kingdom Death: Monster', 'Abstrait') ;
insert into JEUX_THEMES values ( 'Power Grid', 'Construction') ;
insert into JEUX_THEMES values ( 'Tzolk: The Mayan Calendar', 'Construction') ;
insert into JEUX_THEMES values ( 'The Crew: The Quest for Planet Nine', 'Mathematiques') ;
insert into JEUX_THEMES values ( 'Mechs vs. Minions', 'Antiquité') ;
insert into JEUX_THEMES values ( 'Underwater Cities', 'Aventure') ;
insert into JEUX_THEMES values ( 'Star Wars: Imperial Assault', 'Merveilleux') ;
insert into JEUX_THEMES values ( 'Clans of Caledonia', 'Mytholoie') ;
insert into JEUX_THEMES values ( 'Anachrony', 'Abstrait') ;
insert into JEUX_THEMES values ( 'Le Havre', 'Enfant') ;
insert into JEUX_THEMES values ( 'Too Many Bones', 'Fanstastique') ;
insert into JEUX_THEMES values ( 'Through the Ages: A Story of Civilization', 'Histoire') ;
insert into JEUX_THEMES values ( 'Azul', 'Enquete') ;
