insert into JOUEURS_THEMES values ( '1james', 'Histoire') ;
insert into JOUEURS_THEMES values ( '2john', 'Histoire') ;
insert into JOUEURS_THEMES values ( '3robert', 'Espace') ;
insert into JOUEURS_THEMES values ( '4michael', 'Abstrait') ;
insert into JOUEURS_THEMES values ( '5william', 'Espace') ;
insert into JOUEURS_THEMES values ( '6david', 'Mathematiques') ;
insert into JOUEURS_THEMES values ( '7richard', 'Aventure') ;
insert into JOUEURS_THEMES values ( '8charles', 'Survie') ;
insert into JOUEURS_THEMES values ( '9joseph', 'Enfant') ;
insert into JOUEURS_THEMES values ( '10thomas', 'Antiquité ') ;
insert into JOUEURS_THEMES values ( '11christopher', 'Espace') ;
insert into JOUEURS_THEMES values ( '12daniel', 'Mytholoie') ;
insert into JOUEURS_THEMES values ( '13paul', 'Aventure') ;
insert into JOUEURS_THEMES values ( '14mark', 'Antiquité ') ;
insert into JOUEURS_THEMES values ( '15donald', 'Connaissances') ;
insert into JOUEURS_THEMES values ( '16george', 'Fanstastique ') ;
insert into JOUEURS_THEMES values ( '17kenneth', 'Merveilleux') ;
insert into JOUEURS_THEMES values ( '18steven', 'Fanstastique') ;
insert into JOUEURS_THEMES values ( '19edward', 'Antiquité') ;
insert into JOUEURS_THEMES values ( '20brian', 'Mathematiques') ;
insert into JOUEURS_THEMES values ( '21ronald', 'Aventure') ;
insert into JOUEURS_THEMES values ( '22anthony', 'Antiquité ') ;
insert into JOUEURS_THEMES values ( '23kevin', 'Connaissances') ;
insert into JOUEURS_THEMES values ( '24jason', 'Enquete') ;
insert into JOUEURS_THEMES values ( '25matthew', 'Abstrait') ;
insert into JOUEURS_THEMES values ( '26gary', 'Fanstastique ') ;
insert into JOUEURS_THEMES values ( '27timothy', 'Mathematiques') ;
insert into JOUEURS_THEMES values ( '28jose', 'Connaissances') ;
insert into JOUEURS_THEMES values ( '29larry', 'Mytholoie') ;
insert into JOUEURS_THEMES values ( '30jeffrey', 'Histoire') ;
insert into JOUEURS_THEMES values ( '31frank', 'Enfant') ;
insert into JOUEURS_THEMES values ( '32scott', 'Fantastique') ;
insert into JOUEURS_THEMES values ( '33eric', 'Abstrait') ;
insert into JOUEURS_THEMES values ( '34stephen', 'Mytholoie') ;
insert into JOUEURS_THEMES values ( '35andrew', 'Merveilleux') ;
insert into JOUEURS_THEMES values ( '36raymond', 'Abstrait') ;
insert into JOUEURS_THEMES values ( '37gregory', 'Construction') ;
insert into JOUEURS_THEMES values ( '38joshua', 'Enfant') ;
insert into JOUEURS_THEMES values ( '39jerry', 'Enquete') ;
insert into JOUEURS_THEMES values ( '40dennis', 'Construction') ;
insert into JOUEURS_THEMES values ( '41walter', 'Enquete') ;
insert into JOUEURS_THEMES values ( '42patrick', 'Construction') ;
insert into JOUEURS_THEMES values ( '43peter', 'Enfant') ;
insert into JOUEURS_THEMES values ( '44harold', 'Survie') ;
insert into JOUEURS_THEMES values ( '45douglas', 'Aventure') ;
insert into JOUEURS_THEMES values ( '46henry', 'Enquete') ;
insert into JOUEURS_THEMES values ( '47carl', 'Survie') ;
insert into JOUEURS_THEMES values ( '48arthur', 'Construction') ;
insert into JOUEURS_THEMES values ( '49ryan', 'Merveilleux') ;
insert into JOUEURS_THEMES values ( '50roger', 'Connaissances') ;
