-- ============================================================
--    creation des donnees
-- ============================================================

-- JOUEURS
insert into JOUEURS values ( '1james', 'H', 'james', 'h1@gmail.com') ;
insert into JOUEURS values ( '2john', 'JOHNSON', 'john', 'johnson2@gmail.com') ;
insert into JOUEURS values ( '3robert', 'WILLIAMS', 'robert', 'williams3@gmail.com') ;
insert into JOUEURS values ( '4michael', 'JONES', 'michael', 'jones4@gmail.com') ;
insert into JOUEURS values ( '5william', 'BROWN', 'william', 'brown5@gmail.com') ;
insert into JOUEURS values ( '6david', 'DAVIS', 'david', 'davis6@gmail.com') ;
insert into JOUEURS values ( '7richard', 'MILLER', 'richard', 'miller7@gmail.com') ;
insert into JOUEURS values ( '8charles', 'WILSON', 'charles', 'wilson8@gmail.com') ;
insert into JOUEURS values ( '9joseph', 'MOORE', 'joseph', 'moore9@gmail.com') ;
insert into JOUEURS values ( '10thomas', 'TAYLOR', 'thomas', 'taylor10@gmail.com') ;
insert into JOUEURS values ( '11christopher', 'ANDERSON', 'christopher', 'anderson11@gmail.com') ;
insert into JOUEURS values ( '12daniel', 'THOMAS', 'daniel', 'thomas12@gmail.com') ;
insert into JOUEURS values ( '13paul', 'JACKSON', 'paul', 'jackson13@gmail.com') ;
insert into JOUEURS values ( '14mark', 'WHITE', 'mark', 'white14@gmail.com') ;
insert into JOUEURS values ( '15donald', 'HARRIS', 'donald', 'harris15@gmail.com') ;
insert into JOUEURS values ( '16george', 'MARTIN', 'george', 'martin16@gmail.com') ;
insert into JOUEURS values ( '17kenneth', 'THOMPSON', 'kenneth', 'thompson17@gmail.com') ;
insert into JOUEURS values ( '18steven', 'GARCIA', 'steven', 'garcia18@gmail.com') ;
insert into JOUEURS values ( '19edward', 'MARTINEZ', 'edward', 'martinez19@gmail.com') ;
insert into JOUEURS values ( '20brian', 'ROBINSON', 'brian', 'robinson20@gmail.com') ;
insert into JOUEURS values ( '21ronald', 'CLARK', 'ronald', 'clark21@gmail.com') ;
insert into JOUEURS values ( '22anthony', 'RODRIGUEZ', 'anthony', 'rodriguez22@gmail.com') ;
insert into JOUEURS values ( '23kevin', 'LEWIS', 'kevin', 'lewis23@gmail.com') ;
insert into JOUEURS values ( '24jason', 'LEE', 'jason', 'lee24@gmail.com') ;
insert into JOUEURS values ( '25matthew', 'WALKER', 'matthew', 'walker25@gmail.com') ;
insert into JOUEURS values ( '26gary', 'HALL', 'gary', 'hall26@gmail.com') ;
insert into JOUEURS values ( '27timothy', 'ALLEN', 'timothy', 'allen27@gmail.com') ;
insert into JOUEURS values ( '28jose', 'YOUNG', 'jose', 'young28@gmail.com') ;
insert into JOUEURS values ( '29larry', 'HERNANDEZ', 'larry', 'hernandez29@gmail.com') ;
insert into JOUEURS values ( '30jeffrey', 'KING', 'jeffrey', 'king30@gmail.com') ;
insert into JOUEURS values ( '31frank', 'WRIGHT', 'frank', 'wright31@gmail.com') ;
insert into JOUEURS values ( '32scott', 'LOPEZ', 'scott', 'lopez32@gmail.com') ;
insert into JOUEURS values ( '33eric', 'HILL', 'eric', 'hill33@gmail.com') ;
insert into JOUEURS values ( '34stephen', 'SCOTT', 'stephen', 'scott34@gmail.com') ;
insert into JOUEURS values ( '35andrew', 'GREEN', 'andrew', 'green35@gmail.com') ;
insert into JOUEURS values ( '36raymond', 'ADAMS', 'raymond', 'adams36@gmail.com') ;
insert into JOUEURS values ( '37gregory', 'BAKER', 'gregory', 'baker37@gmail.com') ;
insert into JOUEURS values ( '38joshua', 'GONZALEZ', 'joshua', 'gonzalez38@gmail.com') ;
insert into JOUEURS values ( '39jerry', 'NELSON', 'jerry', 'nelson39@gmail.com') ;
insert into JOUEURS values ( '40dennis', 'CARTER', 'dennis', 'carter40@gmail.com') ;
insert into JOUEURS values ( '41walter', 'MITCHELL', 'walter', 'mitchell41@gmail.com') ;
insert into JOUEURS values ( '42patrick', 'PEREZ', 'patrick', 'perez42@gmail.com') ;
insert into JOUEURS values ( '43peter', 'ROBERTS', 'peter', 'roberts43@gmail.com') ;
insert into JOUEURS values ( '44harold', 'TURNER', 'harold', 'turner44@gmail.com') ;
insert into JOUEURS values ( '45douglas', 'PHILLIPS', 'douglas', 'phillips45@gmail.com') ;
insert into JOUEURS values ( '46henry', 'CAMPBELL', 'henry', 'campbell46@gmail.com') ;
insert into JOUEURS values ( '47carl', 'PARKER', 'carl', 'parker47@gmail.com') ;
insert into JOUEURS values ( '48arthur', 'EVANS', 'arthur', 'evans48@gmail.com') ;
insert into JOUEURS values ( '49ryan', 'EDWARDS', 'ryan', 'edwards49@gmail.com') ;
insert into JOUEURS values ( '50roger', 'COLLINS', 'roger', 'collins50@gmail.com') ;


-- ============================================================
--    creation des donnees
-- ============================================================

-- THEME
insert into THEMES values ( 'Abstrait' ) ;
insert into THEMES values ( 'Antiquité' ) ;
insert into THEMES values ( 'Aventure' ) ;
insert into THEMES values ( 'Connaissances' ) ;
insert into THEMES values ( 'Construction' ) ;
insert into THEMES values ( 'Enfant' ) ;
insert into THEMES values ( 'Enquete' ) ;
insert into THEMES values ( 'Espace' ) ;
insert into THEMES values ( 'Fanstastique' ) ;
insert into THEMES values ( 'Histoire' ) ;
insert into THEMES values ( 'Mathematiques' ) ;
insert into THEMES values ( 'Merveilleux' ) ;
insert into THEMES values ( 'Mytholoie' ) ;
insert into THEMES values ( 'Survie' ) ;
insert into THEMES values ( 'Abstrait' ) ;
insert into THEMES values ( 'Antiquité ' ) ;
insert into THEMES values ( 'Aventure' ) ;
insert into THEMES values ( 'Connaissances' ) ;
insert into THEMES values ( 'Construction' ) ;
insert into THEMES values ( 'Enfant' ) ;
insert into THEMES values ( 'Enquete' ) ;
insert into THEMES values ( 'Espace' ) ;
insert into THEMES values ( 'Fanstastique ' ) ;
insert into THEMES values ( 'Histoire' ) ;
insert into THEMES values ( 'Mathematiques' ) ;
insert into THEMES values ( 'Merveilleux' ) ;
insert into THEMES values ( 'Mytholoie' ) ;
insert into THEMES values ( 'Survie' ) ;
insert into THEMES values ( 'Abstrait' ) ;
insert into THEMES values ( 'Antiquité ' ) ;
insert into THEMES values ( 'Aventure' ) ;
insert into THEMES values ( 'Connaissances' ) ;
insert into THEMES values ( 'Construction' ) ;
insert into THEMES values ( 'Enfant' ) ;
insert into THEMES values ( 'Enquete' ) ;
insert into THEMES values ( 'Espace' ) ;
insert into THEMES values ( 'Fanstastique ' ) ;
insert into THEMES values ( 'Histoire' ) ;
insert into THEMES values ( 'Mathematiques' ) ;
insert into THEMES values ( 'Merveilleux' ) ;
insert into THEMES values ( 'Mytholoie' ) ;
insert into THEMES values ( 'Survie' ) ;
insert into THEMES values ( 'Abstrait' ) ;
insert into THEMES values ( 'Antiquité ' ) ;
insert into THEMES values ( 'Aventure' ) ;
insert into THEMES values ( 'Connaissances' ) ;
insert into THEMES values ( 'Construction' ) ;
insert into THEMES values ( 'Enfant' ) ;
insert into THEMES values ( 'Enquete' ) ;
insert into THEMES values ( 'Fantastique' ) ;

-- ============================================================
--    creation des donnees
-- ============================================================

-- MECANISMES

insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Majorité' ) ;
insert into MECANIQUES values ( 'Deck-building' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Guess' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Deck-building ' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Guess' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Deck-building ' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Guess' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Deck-building ' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Majorité' ) ;
insert into MECANIQUES values ( 'Deck-building' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Guess' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Deck-building ' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Course' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Guess' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Pari' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Deck-building ' ) ;
insert into MECANIQUES values ( 'Draft' ) ;
insert into MECANIQUES values ( 'Bluff' ) ;
insert into MECANIQUES values ( 'Connection' ) ;
insert into MECANIQUES values ( 'Guess' ) ;
insert into MECANIQUES values ( 'Combinaison' ) ;
insert into MECANIQUES values ( 'Enigmes' ) ;
insert into MECANIQUES values ( 'Déduction' ) ;
insert into MECANIQUES values ( 'Enchères' ) ;
insert into MECANIQUES values ( 'Majorité ' ) ;
insert into MECANIQUES values ( 'Deck-building ' ) ;

